# Generated by Django 5.2.7 on 2025-12-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('MECH', 'Mechanical'), ('IT', 'Information Technology'), ('CSBS', 'Computer Science & Business Systems'), ('AIML', 'Artifical Intelligence and Machine Learning'), ('AIDS', 'Artifical Intelligence and Data Science'), ('CYS', 'CyberSecurity'), ('OFFICE', 'Kite Office'), ('MBA', 'Master of Business Administration'), ('Innovation', 'Innovation Team'), ('Non-Teaching', 'Non-Teaching Staffs'), ('Placement', 'Placement Department'), ('R&A', 'Robotics & Automation'), ('S&H', 'Science & Humanities'), ('IQSC', 'iqsc')], max_length=50, null=True),
        ),
    ]
